name: superclustering-dnn-cpu
channels:
 - pytorch
 - conda-forge
 - nodefaults
dependencies:
 - python>=3.10
#  - ipykernel
#  - notebook
 - numpy
 - scipy
 - uproot=5.*
 - fsspec-xrootd # for uproot reading from xrootd
 - awkward=2.*
 - hist
 - tqdm
#  - ipykernel # notebooks
#  - ipywidgets # to use tqdm in notebooks
 - matplotlib>=3
 - mplhep>=0.3 # plotting CMS style
 - scikit-learn # for ROC curves 

 - xrootd=5.5.3 # latest version 5.6.8 gives TLS error when accessing eosuser

 - pytorch::pytorch
 - pytorch::cpuonly
 - onnx
 - optuna

#  - pip:
#    - torch-tb-profiler
